name: CI

on:
  # Run on PRs to main branch
  pull_request:
    branches: [ "main" ]
  
  # Run on pushes to feature branches (not main)
  push:
    branches-ignore: [ "main" ]

  # Allow manual triggering
  workflow_dispatch:

# Sets permissions for the workflow
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Restore Ollama models
        uses: actions/cache@v4
        with:
          path: "${HOME}/.ollama/models"
          key: ollama-${{ runner.os }}-${{ hashFiles('**/AiTestConfiguration.java') }}
          restore-keys: |
            ollama-${{ runner.os }}-

      - name: Run tests
        run: ./gradlew test
        
      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: 'Test Results'
          path: 'build/test-results/test/*.xml'
          reporter: 'java-junit'
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            build/test-results/
            build/reports/tests/
